model_path: "best.pt"
camera_sources:
  #- "rtsp://admin:123456@192.168.1.188:554/ch01.264"
  #- "rtsp://admin:123456@192.168.1.189:554/ch01.264"
  - "videos/movie.mp4"


app_type: 1
target_fps: 5
log_level: "DEBUG"
classes:
  - "person"
  - "dump truck"
camera_height: 2  # Camera height in meters
target_resolution: [640, 640]  # Fixed resolution for all inputs
output_path : "output/movie.mp4"